"""Cluster 1: Identity + Org + Auth.

14 tables per plan §11:

- users, workspaces, workspace_slugs, projects, project_slugs
- workspace_members, project_members
- service_accounts, api_keys, api_key_usage
- invitations, credentials
- share_grants, budgets

**Enums use `native_enum=False`** (CHECK-constrained VARCHAR, NOT PG `CREATE TYPE`).
Reason: native enums break per-test schema isolation (enums are global; not
schema-scoped). Cost is small — Python enum still validates at the ORM layer.
Investigator-recommended.

**Polymorphic FK pattern** (api_keys.principal, budgets.principal):
two nullable FK cols + `principal_kind` discriminator + 2 CHECK constraints.
CHECK constraints are NOT autogenerated by Alembic — declared in
`__table_args__` and emitted manually in the migration.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    Uuid,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, INET, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from scryer.server.models.base import Base, SoftDeleteMixin, TimestampMixin
from scryer.server.models.enums import (
    ApiScope,
    BudgetPeriod,
    CredentialProvider,
    InvitationStatus,
    PrincipalKind,
    ProjectRole,
    ProjectVisibility,
    SharePermission,
    WorkspaceRole,
)

# ─────────────────────────────────────────────────────────────────────────────
# users
# ─────────────────────────────────────────────────────────────────────────────


class User(Base, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "users"
    __table_args__ = (
        # Partial unique: soft-deleted users free their email for reuse.
        Index(
            "ux_users_email_active",
            "email",
            unique=True,
            postgresql_where=text("archived_at IS NULL"),
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    email: Mapped[str] = mapped_column(String(320), nullable=False)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Relationships
    owned_workspaces: Mapped[list[Workspace]] = relationship(
        "Workspace", back_populates="owner", lazy="raise"
    )
    workspace_memberships: Mapped[list[WorkspaceMember]] = relationship(
        "WorkspaceMember", back_populates="user", lazy="raise"
    )
    project_memberships: Mapped[list[ProjectMember]] = relationship(
        "ProjectMember", back_populates="user", lazy="raise"
    )
    # Polymorphic-aware: only api_keys whose principal_kind='user' AND principal_user_id=self.id.
    # `lazy="raise"` forces explicit loading; `viewonly=True` because principal_kind is also
    # a column not just an FK.
    api_keys: Mapped[list[ApiKey]] = relationship(
        "ApiKey",
        primaryjoin=(
            "and_(User.id==foreign(ApiKey.principal_user_id), ApiKey.principal_kind=='user')"
        ),
        lazy="raise",
        viewonly=True,
    )


# ─────────────────────────────────────────────────────────────────────────────
# workspaces + slugs + members
# ─────────────────────────────────────────────────────────────────────────────


class Workspace(Base, TimestampMixin, SoftDeleteMixin):
    """Plan §5: billing/team boundary; root of resource hierarchy.

    Slug history (`workspace_slugs`) enforces "no slug ever reclaimed" at the
    application layer (slug INSERT into workspaces also writes a row to
    workspace_slugs). DB-level enforcement (e.g., trigger) deferred to v1.
    """

    __tablename__ = "workspaces"
    __table_args__ = (
        UniqueConstraint("slug"),
        CheckConstraint("active_run_count >= 0", name="active_run_count_nonneg"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    slug: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    owner_user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )

    # Plan §7: keep-alive counter for serverless wake-up
    active_run_count: Mapped[int] = mapped_column(
        Integer, nullable=False, default=0, server_default=text("0")
    )

    owner: Mapped[User] = relationship("User", back_populates="owned_workspaces", lazy="raise")
    projects: Mapped[list[Project]] = relationship(
        "Project", back_populates="workspace", lazy="raise"
    )
    members: Mapped[list[WorkspaceMember]] = relationship(
        "WorkspaceMember", back_populates="workspace", lazy="raise"
    )
    service_accounts: Mapped[list[ServiceAccount]] = relationship(
        "ServiceAccount", back_populates="workspace", lazy="raise"
    )


class WorkspaceSlug(Base):
    """Permanent slug → workspace_id history for redirect (GitHub model).

    Append-only. Old slugs can never be reclaimed by a different workspace
    (enforced at service layer via INSERT-or-error semantics).
    """

    __tablename__ = "workspace_slugs"

    slug: Mapped[str] = mapped_column(String(64), primary_key=True)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    retired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class WorkspaceMember(Base, TimestampMixin):
    __tablename__ = "workspace_members"
    __table_args__ = (
        UniqueConstraint("workspace_id", "user_id", name="uq_workspace_members_workspace_user"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    role: Mapped[WorkspaceRole] = mapped_column(
        Enum(WorkspaceRole, name="workspace_role", native_enum=False, length=32),
        nullable=False,
    )

    workspace: Mapped[Workspace] = relationship("Workspace", back_populates="members", lazy="raise")
    user: Mapped[User] = relationship("User", back_populates="workspace_memberships", lazy="raise")


# ─────────────────────────────────────────────────────────────────────────────
# projects + slugs + members
# ─────────────────────────────────────────────────────────────────────────────


class Project(Base, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "projects"
    __table_args__ = (UniqueConstraint("workspace_id", "slug", name="uq_projects_workspace_slug"),)

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    slug: Mapped[str] = mapped_column(String(64), nullable=False)
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    visibility: Mapped[ProjectVisibility] = mapped_column(
        Enum(ProjectVisibility, name="project_visibility", native_enum=False, length=32),
        nullable=False,
        default=ProjectVisibility.workspace,
    )
    auto_comments: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )

    workspace: Mapped[Workspace] = relationship(
        "Workspace", back_populates="projects", lazy="raise"
    )
    members: Mapped[list[ProjectMember]] = relationship(
        "ProjectMember", back_populates="project", lazy="raise"
    )


class ProjectSlug(Base):
    __tablename__ = "project_slugs"
    __table_args__ = (
        UniqueConstraint("workspace_id", "slug", name="uq_project_slugs_workspace_slug"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    slug: Mapped[str] = mapped_column(String(64), nullable=False)
    project_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    retired_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class ProjectMember(Base, TimestampMixin):
    __tablename__ = "project_members"
    __table_args__ = (
        UniqueConstraint("project_id", "user_id", name="uq_project_members_project_user"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    project_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    role: Mapped[ProjectRole] = mapped_column(
        Enum(ProjectRole, name="project_role", native_enum=False, length=32), nullable=False
    )

    project: Mapped[Project] = relationship("Project", back_populates="members", lazy="raise")
    user: Mapped[User] = relationship("User", back_populates="project_memberships", lazy="raise")


# ─────────────────────────────────────────────────────────────────────────────
# service_accounts
# ─────────────────────────────────────────────────────────────────────────────


class ServiceAccount(Base, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "service_accounts"

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)

    # Per plan §6: owner_user_id null = autonomous; set = "acting on behalf of"
    owner_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    is_active: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=True, server_default=text("true")
    )
    requires_approval: Mapped[bool] = mapped_column(
        Boolean, nullable=False, default=False, server_default=text("false")
    )

    workspace: Mapped[Workspace] = relationship(
        "Workspace", back_populates="service_accounts", lazy="raise"
    )
    owner_user: Mapped[User | None] = relationship("User", lazy="raise")


# ─────────────────────────────────────────────────────────────────────────────
# api_keys + api_key_usage  (POLYMORPHIC FK)
# ─────────────────────────────────────────────────────────────────────────────


class ApiKey(Base, TimestampMixin):
    """Programmatic auth credential. Polymorphic principal (User OR ServiceAccount).

    `key_hash` = sha256(full_key) — the input has 256 bits of entropy so a
    fast hash is sufficient; argon2 here would add ~50ms per request for no
    security benefit. Matches Stripe / GitHub / crates.io.

    See plan §6 (and notepad: investigator-recommended deviation from earlier
    bcrypt locking).
    """

    __tablename__ = "api_keys"
    __table_args__ = (
        # Polymorphic FK: exactly one of (user, service_account) must be set
        CheckConstraint(
            "(principal_user_id IS NOT NULL)::int + "
            "(principal_service_account_id IS NOT NULL)::int = 1",
            name="exactly_one_principal",
        ),
        # Discriminator must agree with which FK is populated
        CheckConstraint(
            "(principal_kind = 'user' AND principal_user_id IS NOT NULL) OR "
            "(principal_kind = 'service_account' AND principal_service_account_id IS NOT NULL)",
            name="principal_kind_matches_fk",
        ),
        Index("ix_api_keys_key_prefix", "key_prefix"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)

    # Polymorphic principal
    principal_kind: Mapped[PrincipalKind] = mapped_column(
        Enum(PrincipalKind, name="principal_kind", native_enum=False, length=32),
        nullable=False,
    )
    # ondelete=RESTRICT: don't silently lose audit trail when user is hard-deleted.
    # Since User uses SoftDeleteMixin, normal flow soft-deletes (RESTRICT not triggered).
    principal_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=True
    )
    principal_service_account_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("service_accounts.id", ondelete="RESTRICT"), nullable=True
    )

    # Display + verification
    key_prefix: Mapped[str] = mapped_column(String(32), nullable=False)
    key_hash: Mapped[str] = mapped_column(String(64), nullable=False)  # sha256 hex
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)

    # Authorization
    scopes: Mapped[list[ApiScope]] = mapped_column(
        ARRAY(Enum(ApiScope, name="api_scope", native_enum=False, length=32)),
        nullable=False,
        default=list,
        server_default=text("'{}'"),
    )
    # allowed_ips removed v0 (deferred enforcement; CONVENTIONS: no fake support)

    # Lifecycle
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    last_used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationships (one populated based on principal_kind)
    user: Mapped[User | None] = relationship(
        "User",
        primaryjoin="ApiKey.principal_user_id==User.id",
        foreign_keys="[ApiKey.principal_user_id]",
        lazy="raise",
    )
    service_account: Mapped[ServiceAccount | None] = relationship(
        "ServiceAccount",
        foreign_keys="[ApiKey.principal_service_account_id]",
        lazy="raise",
    )


class ApiKeyUsage(Base):
    """Lightweight per-request forensics. Separate from full AuditEvent.

    Bigserial PK; no UUID overhead. Two indexes:
    - (api_key_id, id) for "show usage history of this key"
    - (timestamp) for billing/range queries
    """

    __tablename__ = "api_key_usage"
    __table_args__ = (
        Index("ix_api_key_usage_api_key_id_id", "api_key_id", "id"),
        Index("ix_api_key_usage_timestamp", "timestamp"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    api_key_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("api_keys.id", ondelete="CASCADE"), nullable=False
    )
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    ip_address: Mapped[str | None] = mapped_column(INET, nullable=True)
    endpoint: Mapped[str | None] = mapped_column(String(255), nullable=True)
    status_code: Mapped[int | None] = mapped_column(Integer, nullable=True)


# ─────────────────────────────────────────────────────────────────────────────
# invitations
# ─────────────────────────────────────────────────────────────────────────────


class Invitation(Base, TimestampMixin):
    """Signup token. `token_hash` = sha256(token); high-entropy input so
    argon2/bcrypt buys nothing. See ApiKey docstring."""

    __tablename__ = "invitations"
    __table_args__ = (
        Index("ix_invitations_token_hash", "token_hash"),
        # Defensive: invites must have nonzero TTL at creation
        CheckConstraint("expires_at > created_at", name="ttl_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False)  # sha256 hex
    email: Mapped[str | None] = mapped_column(String(320), nullable=True)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    workspace_role: Mapped[WorkspaceRole] = mapped_column(
        Enum(WorkspaceRole, name="workspace_role", native_enum=False, length=32),
        nullable=False,
    )
    project_grants: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    invited_by: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )

    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    used_by_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="SET NULL"), nullable=True
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    @property
    def status(self) -> InvitationStatus:
        """Computed; not stored. Queries that need to filter by status must
        use `WHERE` clauses on the underlying timestamp columns."""
        from scryer.server.models.base import utc_now

        if self.revoked_at is not None:
            return InvitationStatus.revoked
        if self.used_at is not None:
            return InvitationStatus.used
        if self.expires_at < utc_now():
            return InvitationStatus.expired
        return InvitationStatus.pending


# ─────────────────────────────────────────────────────────────────────────────
# credentials  (workspace-scoped; AES-GCM encrypted)
# ─────────────────────────────────────────────────────────────────────────────


class Credential(Base, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "credentials"
    __table_args__ = (
        # GIN for "find credentials user X is allowed to use"
        Index(
            "ix_credentials_restricted_to_user_ids",
            "restricted_to_user_ids",
            postgresql_using="gin",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    provider: Mapped[CredentialProvider] = mapped_column(
        Enum(CredentialProvider, name="credential_provider", native_enum=False, length=32),
        nullable=False,
    )
    # base64(nonce(12) || ciphertext || tag(16))
    encrypted_value: Mapped[str] = mapped_column(Text, nullable=False)
    encryption_key_version: Mapped[int] = mapped_column(Integer, nullable=False)

    # Endpoint URL, org_id, model whitelist, etc.
    metadata_json: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)

    # Optional restriction: only these users can decrypt+use this credential.
    # No FK enforcement (PG arrays don't support per-element FK); validated at
    # service layer.
    restricted_to_user_ids: Mapped[list[uuid.UUID] | None] = mapped_column(
        ARRAY(Uuid), nullable=True
    )


# ─────────────────────────────────────────────────────────────────────────────
# share_grants  (per-resource cross-Project sharing — plan §5)
# ─────────────────────────────────────────────────────────────────────────────


class ShareGrant(Base, TimestampMixin):
    """Per-resource grant for cross-Project sharing.

    `resource_type` is a string (e.g. 'run', 'dataset') — NOT a polymorphic
    FK to specific tables. Resource integrity is enforced at the application
    layer (ID validation on grant). FKs to {run,dataset,...}.id would require
    one nullable column per resource type → unwieldy.
    """

    __tablename__ = "share_grants"
    __table_args__ = (
        UniqueConstraint(
            "resource_type",
            "resource_id",
            "grantee_user_id",
            name="uq_share_grants_resource_grantee",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )
    resource_type: Mapped[str] = mapped_column(String(64), nullable=False)
    resource_id: Mapped[uuid.UUID] = mapped_column(Uuid, nullable=False)
    grantee_user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    permission: Mapped[SharePermission] = mapped_column(
        Enum(SharePermission, name="share_permission", native_enum=False, length=32),
        nullable=False,
    )
    granted_by_user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=False
    )
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


# ─────────────────────────────────────────────────────────────────────────────
# budgets  (POLYMORPHIC FK — same pattern as ApiKey)
# ─────────────────────────────────────────────────────────────────────────────


class Budget(Base, TimestampMixin, SoftDeleteMixin):
    __tablename__ = "budgets"
    __table_args__ = (
        CheckConstraint(
            "(principal_user_id IS NOT NULL)::int + "
            "(principal_service_account_id IS NOT NULL)::int = 1",
            name="exactly_one_principal",
        ),
        CheckConstraint(
            "(principal_kind = 'user' AND principal_user_id IS NOT NULL) OR "
            "(principal_kind = 'service_account' AND principal_service_account_id IS NOT NULL)",
            name="principal_kind_matches_fk",
        ),
        CheckConstraint("period_end > period_start", name="period_positive"),
    )

    id: Mapped[uuid.UUID] = mapped_column(Uuid, primary_key=True, default=uuid.uuid4)
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        Uuid, ForeignKey("workspaces.id", ondelete="CASCADE"), nullable=False
    )

    principal_kind: Mapped[PrincipalKind] = mapped_column(
        Enum(PrincipalKind, name="principal_kind", native_enum=False, length=32),
        nullable=False,
    )
    principal_user_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("users.id", ondelete="RESTRICT"), nullable=True
    )
    principal_service_account_id: Mapped[uuid.UUID | None] = mapped_column(
        Uuid, ForeignKey("service_accounts.id", ondelete="RESTRICT"), nullable=True
    )

    period: Mapped[BudgetPeriod] = mapped_column(
        Enum(BudgetPeriod, name="budget_period", native_enum=False, length=32),
        nullable=False,
    )
    amount_usd: Mapped[Decimal] = mapped_column(Numeric(12, 4), nullable=False)
    period_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    period_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
