"""drop allowed_ips from api_keys

Revision ID: 41b5f1d39d4e
Revises: d708878e5f9e
Create Date: 2026-05-02 03:50:24.670718
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "41b5f1d39d4e"
down_revision: str | None = "d708878e5f9e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_keys", "allowed_ips")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_keys",
        sa.Column(
            "allowed_ips", postgresql.ARRAY(postgresql.INET()), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
