"""cluster4: comments collections

Revision ID: 51ab39f0910d
Revises: a9687fc717c6
Create Date: 2026-05-02 04:20:47.220623
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "51ab39f0910d"
down_revision: str | None = "a9687fc717c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collections",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "purpose",
            sa.Enum(
                "investigation",
                "incident",
                "showcase",
                "other",
                name="collection_purpose",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_collections_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("project_id", "slug", name="uq_collections_project_slug"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Uuid(), nullable=True),
        sa.Column(
            "author_kind",
            sa.Enum(
                "user",
                "service_account",
                "cron",
                "system",
                name="actor_kind",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("author_service_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum("user", "agent", "system", name="comment_kind", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("mentions", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reply_to_comment_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_service_account_id"],
            ["service_accounts.id"],
            name=op.f("fk_comments_author_service_account_id_service_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_comments_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_comments_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reply_to_comment_id"],
            ["comments.id"],
            name=op.f("fk_comments_reply_to_comment_id_comments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
    )
    op.create_index("ix_comments_project_id_id", "comments", ["project_id", "id"], unique=False)
    op.create_index(
        "ix_comments_resource_type_resource_id",
        "comments",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_table(
        "collection_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("member_type", sa.String(length=64), nullable=False),
        sa.Column("member_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("group", sa.String(length=128), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_collection_members_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collection_members")),
        sa.UniqueConstraint(
            "collection_id", "member_type", "member_id", name="uq_collection_members_unique"
        ),
    )
    op.create_index(
        "ix_collection_members_collection_position",
        "collection_members",
        ["collection_id", "position"],
        unique=False,
    )
    op.create_table(
        "comment_versions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("comment_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("structured", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("edited_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["comment_id"],
            ["comments.id"],
            name=op.f("fk_comment_versions_comment_id_comments"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comment_versions")),
        sa.UniqueConstraint("comment_id", "version", name="uq_comment_versions_comment_version"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("comment_versions")
    op.drop_index("ix_collection_members_collection_position", table_name="collection_members")
    op.drop_table("collection_members")
    op.drop_index("ix_comments_resource_type_resource_id", table_name="comments")
    op.drop_index("ix_comments_project_id_id", table_name="comments")
    op.drop_table("comments")
    op.drop_table("collections")
    # ### end Alembic commands ###
